---
# Monitoring configuration defaults
monitoring_stack: "prometheus"  # prometheus, zabbix, nagios
monitoring_enable_metrics_collection: true
monitoring_enable_log_aggregation: true
monitoring_enable_alerting: true

# Prometheus configuration
monitoring_prometheus_version: "2.40.0"
monitoring_prometheus_port: 9090
monitoring_prometheus_retention: "30d"
monitoring_prometheus_storage_path: "/var/lib/prometheus"

# Node Exporter configuration
monitoring_node_exporter_version: "1.5.0"
monitoring_node_exporter_port: 9100

# Alertmanager configuration
monitoring_alertmanager_version: "0.25.0"
monitoring_alertmanager_port: 9093

# Grafana configuration
monitoring_grafana_version: "9.3.0"
monitoring_grafana_port: 3000
monitoring_grafana_admin_password: "{{ vault_grafana_password | default('admin') }}"

# Monitoring targets
monitoring_monitor_system_metrics: true
monitoring_monitor_application_metrics: true
monitoring_monitor_network_metrics: true
monitoring_monitor_security_events: true

# Alert thresholds
monitoring_cpu_alert_threshold: 80
monitoring_memory_alert_threshold: 85
monitoring_disk_alert_threshold: 90
monitoring_load_alert_threshold: 5.0

# Notification channels
monitoring_slack_webhook_url: ""
monitoring_email_smtp_host: ""
monitoring_email_smtp_port: 587
monitoring_email_from: "msp-platform@example.com"
monitoring_email_to: "admin@example.com"

# Log aggregation
monitoring_enable_rsyslog: true
monitoring_enable_logrotate: true
monitoring_log_retention_days: 30
monitoring_centralized_logging: false

# Client-specific monitoring
monitoring_client_dashboards: true
monitoring_custom_metrics: []
monitoring_interval: 60  # seconds