---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  vars:
    # Minimal path: create groups + admin user + sudoers
    manage_groups: true
    setup_sudo_access: true
    enforce_password_policy: false
    manage_users: true
    manage_ssh_keys: false
    configure_pam: false
    audit_user_access: false
    disable_unused_accounts: false
    service_accounts: []
    client_users: []
    admin_users:
      - name: molecule-admin
        comment: Molecule Admin
        groups: ["msp-admins"]
        sudo_access: true
        state: present
  roles:
    - role: user-management
