---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Assert OS facts are available
      ansible.builtin.assert:
        that:
          - ansible_facts.os_family is defined
        success_msg: "Facts gathered successfully"
        fail_msg: "Facts not available"
