---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Assert OS facts are available
      ansible.builtin.assert:
        that:
          - ansible_facts.os_family is defined
        success_msg: "Facts gathered successfully"
        fail_msg: "Facts not available"

    - name: Gather passwd and group entries
      ansible.builtin.getent:
        database: "{{ item }}"
      loop:
        - passwd
        - group

    - name: Determine admin group
      ansible.builtin.set_fact:
        admin_primary_group: "{{ 'wheel' if ansible_facts.os_family == 'RedHat' else 'sudo' }}"

    - name: Assert admin groups exist
      ansible.builtin.assert:
        that:
          - getent_group['msp-admins'] is defined
        success_msg: "msp-admins group exists"
        fail_msg: "msp-admins group missing"

    - name: Assert molecule-admin user exists
      ansible.builtin.assert:
        that:
          - getent_passwd['molecule-admin'] is defined
        success_msg: "molecule-admin user present"
        fail_msg: "molecule-admin user missing"

    - name: Determine molecule-admin home
      ansible.builtin.set_fact:
        molecule_admin_home: "{{ getent_passwd['molecule-admin'][4] }}"

    - name: Check authorized_keys for molecule-admin
      ansible.builtin.stat:
        path: "{{ molecule_admin_home }}/.ssh/authorized_keys"
      register: ak

    - name: Assert authorized_keys exists with correct mode
      ansible.builtin.assert:
        that:
          - ak.stat.exists
          - ak.stat.mode is defined and ak.stat.mode | regex_search('.*600$')
        success_msg: "authorized_keys present with correct mode"
        fail_msg: "authorized_keys missing or wrong mode"

    - name: Read authorized_keys
      ansible.builtin.slurp:
        path: "{{ molecule_admin_home }}/.ssh/authorized_keys"
      register: ak_file

    - name: Assert authorized_keys contains expected key
      ansible.builtin.assert:
        that:
          - (ak_file.content | b64decode) is search('MSPMoleculeTestKey')
        success_msg: "authorized_keys contains test key"
        fail_msg: "authorized_keys missing test key"

    - name: Get molecule-admin groups
      ansible.builtin.command: id -nG molecule-admin
      register: mgroups
      changed_when: false

    - name: Determine admin group
      ansible.builtin.set_fact:
        admin_primary_group: "{{ 'wheel' if ansible_facts.os_family == 'RedHat' else 'sudo' }}"

    - name: Assert molecule-admin is in required groups
      ansible.builtin.assert:
        that:
          - mgroups.stdout is search('(^|\s)msp-admins(\s|$)')
          - mgroups.stdout is search('(^|\s)' ~ admin_primary_group ~ '(\s|$)')
        success_msg: "molecule-admin group membership OK"
        fail_msg: "molecule-admin missing required group membership"

    - name: Check sudoers drop-in
      ansible.builtin.stat:
        path: /etc/sudoers.d/msp-admins
      register: sudoers_drop

    - name: Assert sudoers drop-in exists with correct mode
      ansible.builtin.assert:
        that:
          - sudoers_drop.stat.exists
          - sudoers_drop.stat.mode is defined and sudoers_drop.stat.mode | regex_search('.*440$')
        success_msg: "sudoers drop-in OK"
        fail_msg: "sudoers drop-in missing or wrong mode"
