---
# Lab vSphere Inventory (environment-specific only)
# Reuses global playbooks in ansible/playbooks/

all:
  children:
    vcenter:
      hosts:
        vcenter.lab.local:
          ansible_host: vcenter.lab.local
          ansible_connection: local
    k3s_masters:
      hosts:
        k3s-01.lab.local:
        k3s-02.lab.local:
        k3s-03.lab.local:
    k3s_workers:
      hosts:
        k3s-04.lab.local:
        k3s-05.lab.local:
    postgres:
      hosts:
        pg-01.lab.local:
    redis:
      hosts:
        redis-01.lab.local:
    registry:
      hosts:
        harbor-01.lab.local:
    minio:
      hosts:
        minio-01.lab.local:
    vault:
      hosts:
        vault-01.lab.local:
    broker:
      hosts:
        frps-01.lab.local:
        frps-02.lab.local:
    clients_linux:
      hosts:
        client-01.lab.local:
        client-02.lab.local:
        client-03.lab.local:
    clients_windows:
      hosts:
        client-04.lab.local:
        client-05.lab.local:
        client-06.lab.local:

