---
profile: production

exclude_paths:
  - .cache/
  - .github/
  - molecule/
  - tests/
  - .ansible/
  - venv/
  - .venv/
  - Reference/
  # Exclude vendored third-party roles installed by galaxy during CI
  - ansible/roles/ansible-lockdown.*

skip_list:
  - galaxy[no-changelog]
  - galaxy[version-incorrect]
  - no-changed-when
  - command-instead-of-module
  - run-once[task]
  - key-order[task]  # Cosmetic issue, not breaking
  - ignore-errors  # Best practice but not breaking
  - risky-shell-pipe  # Best practice but not breaking
  - jinja[spacing]  # Cosmetic issue

warn_list:
  - experimental
  - yaml[line-length]

offline: true
