---
profile: production

exclude_paths:
  - .cache/
  - .github/
  - molecule/
  - tests/
  - .ansible/
  - venv/
  - .venv/
  - Reference/

skip_list:
  - galaxy[no-changelog]
  - galaxy[version-incorrect]
  - risky-file-permissions
  - no-changed-when
  - command-instead-of-module
  - package-latest
  - run-once[task]

warn_list:
  - experimental
  - yaml[line-length]

offline: true