---
extends: default

rules:
  # Line length limit
  line-length:
    max: 180
    level: warning
    allow-non-breakable-words: true

  # Indentation
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false

  # Trailing spaces
  trailing-spaces: disable

  # Empty lines
  empty-lines:
    max: 2
    max-start: 0
    max-end: 1

  # Comments
  comments:
    min-spaces-from-content: 1
  comments-indentation: disable

  # Octal values
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true

  # Document start
  document-start:
    present: true

  # End-of-file newline
  new-line-at-end-of-file: disable

  # Truthy values
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']
    check-keys: true

  # Brackets
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1

  # Braces
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1

ignore: |
  .github/
  molecule/
  .ansible/
  venv/
  collections/
  *.enc
  vault.yml
  Reference/
  infrastructure/
  msp-infrastructure/
  ansible/roles/compliance-frameworks/
  ansible/roles/client-onboarding/
  ansible/roles/bastion-infrastructure/
  ansible/roles/reverse-tunnel-infrastructure/
  ansible/roles/msp-infrastructure/
  ansible/roles/graceful-disconnection/
  # Known non-playbook reference file with YAML structure issues
  ansible/playbooks/monitoring-alerting-original.yml
  # Ignore galaxy-installed third-party roles (vendored during CI)
  ansible/roles/ansible-lockdown.*
