---
# Ansible Galaxy Dependencies for MSP Platform
# Community roles for enhanced functionality and testing

collections:
  # Core Ansible collections
  - name: ansible.posix
    version: ">=1.4.0"
  - name: community.general
    version: ">=6.0.0"
  - name: community.crypto
    version: ">=2.10.0"
  - name: community.docker
    version: ">=3.0.0"
  - name: containers.podman
    version: ">=1.9.0"

  # Security and compliance collections
  - name: community.hashi_vault
    version: ">=4.0.0"
  - name: ansible.netcommon
    version: ">=4.1.0"

  # Cloud provider collections (optional)
  - name: amazon.aws
    version: ">=5.0.0"
  - name: azure.azcollection
    version: ">=1.14.0"
  - name: google.cloud
    version: ">=1.1.0"

roles:
  # ansible-lockdown security hardening roles - integrated into MSP platform
  # CIS Benchmarks for comprehensive system hardening
  - name: ansible-lockdown.RHEL8-CIS
    src: https://github.com/ansible-lockdown/RHEL8-CIS
    version: main
    
  - name: ansible-lockdown.RHEL9-CIS
    src: https://github.com/ansible-lockdown/RHEL9-CIS
    version: main
    
  - name: ansible-lockdown.UBUNTU20-CIS
    src: https://github.com/ansible-lockdown/UBUNTU20-CIS
    version: main
    
  - name: ansible-lockdown.UBUNTU22-CIS
    src: https://github.com/ansible-lockdown/UBUNTU22-CIS
    version: main

  # DISA STIG compliance for defense contractors and federal agencies
  - name: ansible-lockdown.RHEL8-STIG
    src: https://github.com/ansible-lockdown/RHEL8-STIG
    version: main
    
  - name: ansible-lockdown.RHEL9-STIG
    src: https://github.com/ansible-lockdown/RHEL9-STIG
    version: main

  - name: dev-sec.ssh-hardening
    # Use latest release from Ansible Galaxy to avoid branch mismatches

  - name: dev-sec.os-hardening
    # Use latest release from Ansible Galaxy to avoid branch mismatches

  # Monitoring and observability
  - name: cloudalchemy.prometheus

  - name: cloudalchemy.alertmanager

  - name: cloudalchemy.grafana

  - name: cloudalchemy.node_exporter

  # Audit and logging
  - name: willshersystems.sshd

  # Backup solutions
  - name: geerlingguy.repo-epel

  - name: geerlingguy.repo-remi

  # Container and orchestration
  - name: geerlingguy.docker

  - name: geerlingguy.pip

  # Testing and development
  - name: geerlingguy.git

  # Note: molecule is installed via pip in CI/CD pipeline
