---
- name: Determine chrony service name per OS
  ansible.builtin.set_fact:
    chrony_service: "{{ 'chronyd' if ansible_facts.os_family == 'RedHat' else 'chrony' }}"

- name: Install NTP package (chrony)
  ansible.builtin.package:
    name: chrony
    state: present
  tags:
    - system
    - time

- name: Enable and start NTP service
  ansible.builtin.systemd:
    name: "{{ chrony_service }}"
    enabled: true
    state: started
    daemon_reload: true
  tags:
    - system
    - time
