---
- name: Update apt cache (Debian family)
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_facts.os_family == 'Debian'
  tags: [packages, updates]

- name: Upgrade packages (Debian family)
  ansible.builtin.apt:
    upgrade: yes
  when: ansible_facts.os_family == 'Debian'
  tags: [packages, updates]

- name: Upgrade packages (RedHat family)
  ansible.builtin.yum:
    name: '*'
    state: latest
  when: ansible_facts.os_family == 'RedHat'
  tags: [packages, updates]
