---
# MSP Compliance Frameworks Role Defaults
# Integrated ansible-lockdown patterns for multi-framework support

# Framework Selection (ansible-lockdown integration pattern)
compliance_framework: "{{ compliance_framework | default('cmmc') }}" # cmmc, cis, stig, soc2, hipaa
compliance_level: "{{ compliance_level | default('level2') }}"
compliance_profile: "{{ compliance_profile | default('server') }}" # server, workstation

# MSP Client Configuration
client_name: "{{ client_name | mandatory }}"
client_tier: "{{ client_tier | default('professional') }}" # foundation, professional, enterprise
client_environment: "{{ client_environment | default('production') }}"

# ansible-lockdown inspired control variables
disruption_high: "{{ disruption_high | default(false) }}"
run_audit: "{{ run_audit | default(false) }}"
skip_reboot: "{{ skip_reboot | default(true) }}"

# Framework Control Categories (unified across frameworks)
# Following ansible-lockdown variable naming patterns
compliance_cat1_patch: "{{ compliance_cat1_patch | default(true) }}" # High severity
compliance_cat2_patch: "{{ compliance_cat2_patch | default(true) }}" # Medium severity
compliance_cat3_patch: "{{ compliance_cat3_patch | default(false) }}" # Low severity

# Control Family Enablement (framework-agnostic)
enable_access_control: "{{ enable_access_control | default(true) }}"
enable_audit_accountability: "{{ enable_audit_accountability | default(true) }}"
enable_config_management: "{{ enable_config_management | default(true) }}"
enable_identification_auth: "{{ enable_identification_auth | default(true) }}"
enable_system_protection: "{{ enable_system_protection | default(true) }}"
enable_system_integrity: "{{ enable_system_integrity | default(true) }}"

# Access Control (AC) Configuration
cmmc_ac_allowed_users:
  - ansible-service
  - "{{ ansible_user | default('admin') }}"

cmmc_ac_ssh_port: 2022
cmmc_ac_disable_password_auth: true
cmmc_ac_require_pubkey_auth: true
cmmc_ac_max_auth_tries: 3
cmmc_ac_login_grace_time: 60

# Audit and Accountability (AU) Configuration
cmmc_au_enable_auditd: true
cmmc_au_log_retention_days: 90
cmmc_au_max_log_file_size: 100 # MB
cmmc_au_space_left_action: "email"
cmmc_au_admin_space_left_action: "suspend"

# Configuration Management (CM) Configuration
cmmc_cm_enable_aide: true
cmmc_cm_aide_check_frequency: "daily"
cmmc_cm_baseline_config_path: "/etc/cmmc/baseline"

# Identification and Authentication (IA) Configuration  
cmmc_ia_password_min_length: 14
cmmc_ia_password_complexity: true
cmmc_ia_account_lockout_attempts: 5
cmmc_ia_account_lockout_duration: 900 # 15 minutes

# System and Communications Protection (SC) Configuration
cmmc_sc_disable_weak_protocols: true
cmmc_sc_enable_firewall: true
cmmc_sc_allowed_services:
  - ssh
  - https

# System and Information Integrity (SI) Configuration
cmmc_si_enable_antivirus: false # Most Linux environments use other methods
cmmc_si_enable_host_intrusion_detection: true
cmmc_si_enable_file_integrity_monitoring: true

# MSP Reporting Configuration (enhanced)
compliance_reporting_enabled: true
compliance_reporting_format: "json" # json, yaml, html, sarif
compliance_reporting_destination: "/var/log/msp/{{ client_name }}/compliance"
compliance_send_reports_to_msp: true
compliance_msp_reporting_endpoint: "{{ msp_reporting_url | default('') }}"
compliance_audit_timestamp: "{{ ansible_date_time.iso8601 }}"

# ansible-lockdown inspired audit configuration
compliance_audit_content: [] # Populated during execution
compliance_audit_only: "{{ compliance_audit_only | default(false) }}"

# Emergency Response Configuration
cmmc_emergency_contact: "{{ emergency_contact | default('') }}"
cmmc_incident_response_enabled: true
cmmc_auto_isolation_enabled: false

# Validation and Testing (ansible-lockdown patterns)
compliance_validation_enabled: true
compliance_validation_frequency: "daily"
compliance_validation_on_change: true
compliance_test_mode: "{{ compliance_test_mode | default(false) }}" # Dry-run mode

# Configuration Management
compliance_config_backup_enabled: true
compliance_config_backup_frequency: "daily"
compliance_config_backup_retention: 30 # days
compliance_preserve_original: true # Keep original configs

# MSP Service Integration
msp_monitoring_integration: "{{ msp_monitoring_integration | default(true) }}"
msp_backup_integration: "{{ msp_backup_integration | default(true) }}"
msp_user_management_integration: "{{ msp_user_management_integration | default(true) }}"
