---
# Common role defaults for MSP platform
timezone: "UTC"
ntp_servers:
  - "0.pool.ntp.org"
  - "1.pool.ntp.org"
  - "2.pool.ntp.org"
  - "3.pool.ntp.org"

# Package management (safe defaults for CI)
update_packages: false
install_essential_packages: true
essential_packages:
  - curl
  - wget
  - git
  - vim
  - htop
  - rsync
  - unzip
  - net-tools
  - tcpdump
  - lsof
  - python3
  - python3-pip

# System optimization (disabled until implemented)
optimize_sysctl: false
enable_firewall: false
configure_logging: false
setup_users: false

# Security hardening (disabled until implemented)
disable_unused_services: false
configure_ssh_hardening: false
setup_fail2ban: false
enable_audit_logging: false

# Performance tuning (not used in minimal path)
tune_kernel_parameters: false
optimize_network_settings: false
configure_swap: false

# Backup and monitoring
install_monitoring_agent: false
configure_log_rotation: true
setup_system_backups: false
