---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: onboarding-ubuntu22
    image: ubuntu:22.04
    dockerfile: ../resources/Dockerfile.ubuntu
    pre_build_image: false
    privileged: true
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host

  - name: onboarding-rocky9
    image: rockylinux:9
    dockerfile: ../resources/Dockerfile.rocky
    pre_build_image: false
    privileged: true
    command: /usr/sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host

provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      stdout_callback: yaml
      bin_ansible_callbacks: true
  env:
    ANSIBLE_ROLES_PATH: "../../../"
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python3

verifier:
  name: ansible

scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
