

# Additional MSP Infrastructure Components
- name: Deploy MSP Monitoring Stack
  hosts: msp_monitoring
  become: true
  gather_facts: true
  vars:
    monitoring_stack_version: "1.0.0"
    
  roles:
    - role: common
      tags: [common]
      
    - role: monitoring
      tags: [monitoring, metrics]
      vars:
        monitoring_type: "centralized"
        enable_alertmanager: true
        enable_grafana: true
        
    - role: network-security
      tags: [security, firewall]
      vars:
        firewall_mode: "msp_monitoring"

  post_tasks:
    - name: Configure MSP monitoring endpoints
      ansible.builtin.template:
        src: ../roles/monitoring/templates/prometheus-msp.yml.j2
        dest: /etc/prometheus/prometheus.yml
        backup: true
      notify: restart prometheus
      tags: [configuration]

# MSP Client Management Infrastructure
- name: Deploy Client Management Infrastructure
  hosts: msp_client_managers
  become: true
  gather_facts: true
  
  roles:
    - role: common
      tags: [common]
      
    - role: client-management
      tags: [client-mgmt]
      vars:
        enable_wireguard_hub: true
        enable_ssh_jumphost: true
        enable_git_repos: true
        
    - role: network-security
      tags: [security, vpn]
      vars:
        firewall_mode: "client_connectivity"

  post_tasks:
    - name: Initialize client repository structure
      ansible.builtin.file:
        path: "/opt/msp/clients/{{ item }}"
        state: directory
        owner: git
        group: git
        mode: '0755'
      loop:
        - repositories
        - configs
        - logs
        - backups
      tags: [initialization]