---
- name: Gather service facts for node_exporter check
  ansible.builtin.service_facts: {}

- name: Assert node exporter service present when requested
  ansible.builtin.assert:
    that:
      - (ansible_facts.services['prometheus-node-exporter.service'] is defined) or (ansible_facts.services['node_exporter.service'] is defined)
    success_msg: "node_exporter service present"
    fail_msg: "node_exporter service missing"
